import type {
  Category,
  DocumentSummary,
  ProcessingJob,
  ProductDetail,
  ProductSummary,
  ReviewTask,
} from "./types";

export const demoCategories: Category[] = [
  { id: "cat-qi", nameZhTw: "Qi 無線充電", parentId: null },
  { id: "cat-mount", nameZhTw: "磁吸支架", parentId: null },
  { id: "cat-desktop", nameZhTw: "桌面支架", parentId: null },
  { id: "cat-hub", nameZhTw: "Hub／Docking", parentId: null },
];

export const demoDocuments: DocumentSummary[] = [
  {
    id: "doc-001",
    title: "三合一桌面无线充20260629R.pdf",
    extension: "pdf",
    documentType: "product",
    sensitivity: "general",
    processingStatus: "completed",
    sourcePath: "Qi無線充電/多合一充電支架/三合一桌面无线充20260629R.pdf",
    version: 1,
    byteSize: 4_195_106,
    pageCount: 2,
    updatedAt: "2026-06-29T10:31:15Z",
  },
  {
    id: "doc-002",
    title: "HUB_DOCKING產品分析.xlsx",
    extension: "xlsx",
    documentType: "product",
    sensitivity: "commercial",
    processingStatus: "needs_review",
    sourcePath: "_外購/Hub Docking/HUB_DOCKING產品分析.xlsx",
    version: 1,
    byteSize: 1_824_500,
    pageCount: 6,
    updatedAt: "2026-07-18T03:22:00Z",
  },
  {
    id: "doc-003",
    title: "风扇报价表.xlsx",
    extension: "xlsx",
    documentType: "quote",
    sensitivity: "commercial",
    processingStatus: "completed",
    sourcePath: "_外購/風扇廠商/风扇报价表.xlsx",
    version: 2,
    byteSize: 684_002,
    pageCount: 4,
    updatedAt: "2026-07-21T08:14:00Z",
  },
  {
    id: "doc-004",
    title: "COMART 2026 Heavy Duty Mount 20260212 updated.pdf",
    extension: "pdf",
    documentType: "product",
    sensitivity: "general",
    processingStatus: "completed",
    sourcePath: "強固型支架/COMART 2026 Heavy Duty Mount 20260212 updated.pdf",
    version: 1,
    byteSize: 12_145_800,
    pageCount: 18,
    updatedAt: "2026-02-12T02:00:00Z",
  },
];

const products: ProductDetail[] = [
  {
    id: "product-id-001a",
    nameOriginal: "三合一桌面无线充",
    nameZhTw: "三合一折疊式桌面無線充電座",
    nameEn: "3-in-1 Foldable Desktop Wireless Charger",
    nameVi: "Đế sạc không dây để bàn gập 3 trong 1",
    brand: null,
    modelNumbers: ["ID-001A"],
    category: demoCategories[0],
    functions: ["手機無線充電", "耳機充電", "Apple Watch 充電", "折疊支架"],
    keywords: ["三合一", "折疊", "桌面", "Qi", "MagSafe", "旅行"],
    suppliers: [],
    confirmationStatus: "ai_high_confidence",
    documentCount: 1,
    updatedAt: "2026-07-30T07:24:00Z",
    specifications: [
      {
        id: "spec-1",
        name: "展開長度",
        valueNumber: 193,
        unit: "mm",
        sourceText: "193mm",
        confirmationStatus: "ai_high_confidence",
      },
      {
        id: "spec-2",
        name: "寬度",
        valueNumber: 61,
        unit: "mm",
        sourceText: "61mm",
        confirmationStatus: "ai_high_confidence",
      },
      {
        id: "spec-3",
        name: "折疊厚度",
        valueNumber: 11,
        unit: "mm",
        sourceText: "11mm",
        confirmationStatus: "ai_high_confidence",
      },
    ],
    evidence: [
      {
        id: "ev-1",
        fieldName: "型號",
        sourceLabel: "三合一桌面无线充20260629R.pdf",
        sourceLocator: "第 1 頁",
        excerpt: "ID-001A",
        confirmationStatus: "ai_high_confidence",
      },
      {
        id: "ev-2",
        fieldName: "尺寸",
        sourceLabel: "三合一桌面无线充20260629R.pdf",
        sourceLocator: "第 2 頁",
        excerpt: "193mm × 61mm × 11mm",
        confirmationStatus: "ai_high_confidence",
      },
    ],
    documents: [demoDocuments[0]],
    latestConfirmedQuote: null,
  },
  {
    id: "product-id-001b",
    nameOriginal: "二合一桌面无线充",
    nameZhTw: "二合一折疊式桌面無線充電座",
    nameEn: "2-in-1 Foldable Desktop Wireless Charger",
    nameVi: "Đế sạc không dây để bàn gập 2 trong 1",
    brand: null,
    modelNumbers: ["ID-001B"],
    category: demoCategories[0],
    functions: ["手機無線充電", "耳機充電", "折疊支架"],
    keywords: ["二合一", "折疊", "桌面", "Qi", "MagSafe"],
    suppliers: [],
    confirmationStatus: "needs_review",
    documentCount: 1,
    updatedAt: "2026-07-30T07:23:00Z",
    specifications: [],
    evidence: [
      {
        id: "ev-3",
        fieldName: "型號",
        sourceLabel: "三合一桌面无线充20260629R.pdf",
        sourceLocator: "第 2 頁",
        excerpt: "ID-001B",
        confirmationStatus: "ai_high_confidence",
      },
    ],
    documents: [demoDocuments[0]],
    latestConfirmedQuote: null,
  },
  {
    id: "product-heavy",
    nameOriginal: "Heavy Duty Mount",
    nameZhTw: "強固型磁吸支架",
    nameEn: "Heavy Duty Magnetic Mount",
    nameVi: "Giá đỡ từ tính chịu lực",
    brand: "COMART",
    modelNumbers: ["HDM-26"],
    category: demoCategories[1],
    functions: ["17mm 球頭", "磁吸固定", "車用支架"],
    keywords: ["強固", "車用", "磁吸", "球頭"],
    suppliers: [],
    confirmationStatus: "human_confirmed",
    documentCount: 1,
    updatedAt: "2026-07-25T04:10:00Z",
    specifications: [],
    evidence: [],
    documents: [demoDocuments[3]],
    latestConfirmedQuote: null,
  },
];

export const demoProducts: ProductSummary[] = products;
export const demoProductDetails = products;

export const demoJobs: ProcessingJob[] = [
  {
    id: "job-1",
    documentTitle: "HUB_DOCKING產品分析.xlsx",
    status: "needs_review",
    progress: 86,
    message: "偵測到 3 個可能重複型號",
    createdAt: "2026-07-30T06:10:00Z",
    updatedAt: "2026-07-30T06:18:00Z",
  },
  {
    id: "job-2",
    documentTitle: "三合一桌面无线充20260629R.pdf",
    status: "completed",
    progress: 100,
    message: "完成：建立 2 個產品變體",
    createdAt: "2026-07-30T05:02:00Z",
    updatedAt: "2026-07-30T05:04:00Z",
  },
];

export const demoReviewTasks: ReviewTask[] = [
  {
    id: "review-1",
    type: "product_split",
    title: "確認是否拆分為兩個產品",
    description: "文件同時出現 ID-001A 與 ID-001B，AI 建議建立兩個變體。",
    documentTitle: "三合一桌面无线充20260629R.pdf",
    priority: "high",
    createdAt: "2026-07-30T05:04:00Z",
  },
  {
    id: "review-2",
    type: "supplier",
    title: "廠商僅由路徑推定",
    description: "文件內文未出現公司名稱，需要人工確認廠商關聯。",
    documentTitle: "HUB_DOCKING產品分析.xlsx",
    priority: "normal",
    createdAt: "2026-07-30T06:18:00Z",
  },
];
